// 画像パスの一元管理。差し替えは public/ 配下のファイルを置き換えるだけでよい。
export const images = {
  logo: {
    full: "/logo/takoda99-logo.png",
    mark: "/logo/takoda99-logo-mark.png",
    title: "/logo/takoda99-title.png",
  },
  screens: {
    matchMain: "/screens/match-main.png",
    matchIngame: "/screens/match-ingame.png",
    matchmaking: "/screens/matchmaking.png",
    standCloseup: "/screens/stand-closeup.png",
    queuePatience: "/screens/queue-patience.png",
    typingHighlight: "/screens/typing-highlight.png",
    burntTakoyaki: "/screens/burnt-takoyaki.png",
    stormAlert: "/screens/storm-alert.png",
    eliminated: "/screens/eliminated.png",
    result: "/screens/result.png",
    title: "/screens/title.png",
    debugPanel: "/screens/debug-panel.png",
  },
  characters: {
    normal: "/characters/customer-normal.png",
    bonus: "/characters/customer-bonus.png",
    claimer: "/characters/customer-claimer.png",
    buzz: "/characters/customer-buzz.png",
    comedian: "/characters/customer-comedian.png",
  },
  art: {
    stand: "/art/stand.png",
    takoyaki: "/art/takoyaki.png",
    takoyakiBurnt: "/art/takoyaki-burnt.png",
    lantern: "/art/lantern.png",
    background: "/art/background.png",
    rough: "/art/rough.png",
    uiMock: "/art/ui-mock.png",
  },
  dev: {
    sddIndex: "/dev/sdd-index.png",
    archDiagram: "/dev/architecture.png",
    claudeMd: "/dev/claude-md.png",
    issues: "/dev/issues.png",
    repoTree: "/dev/repo-tree.png",
    configFront: "/dev/config-front.png",
    matchsimLog: "/dev/matchsim-log.png",
    gcpConsole: "/dev/gcp-console.png",
  },
  team: {
    cashew: "/team/cashew.png",
    rise: "/team/ri-se.png",
    tamatya: "/team/tamatya.png",
    devPhoto: "/team/dev-photo.png",
  },
  favicon: "/favicon.png",
  ogp: "/ogp.png",
};
